### ISSUE TITLE
[依頼]chat-space挙動確認

### ISSUE THREAD

**Issue by gangelion** [gangelion/chat-space#13]
# IPアドレス
18.178.33.110

**Comment by kohei-isoda** [comment]
小島さん、ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by gangelion** [comment]
> 小島さん、ご提出ありがとうございます！
> 確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
> おめでとうございます！

## ありがとうございました！

**Comment by kohei-isoda** [comment]
いえいえ、とんでもございません！
これからが本番ですね、新たな目標を目指して突き進んでください✨
